/* DO NOT EDIT THIS FILE - it is machine generated */
#include <JavaVM/jni.h>
/* Header for class com_aerofs_lib_os_GrowlApplicationBridge */

#ifndef _Included_com_aerofs_growl_GrowlApplicationBridge
#define _Included_com_aerofs_growl_GrowlApplicationBridge
#ifdef __cplusplus
extern "C" {
#endif
    /*
     * Class:     com_aerofs_growl_GrowlApplicationBridge
     * Method:    _isMistEnabled
     * Signature: ()Z
     */
    JNIEXPORT jboolean JNICALL Java_com_aerofs_growl_GrowlApplicationBridge__1isMistEnabled
    (JNIEnv *, jobject);
    
    /*
     * Class:     com_aerofs_growl_GrowlApplicationBridge
     * Method:    _isGrowlRunning
     * Signature: ()Z
     */
    JNIEXPORT jboolean JNICALL Java_com_aerofs_growl_GrowlApplicationBridge__1isGrowlRunning
    (JNIEnv *, jobject);
    
    /*
     * Class:     com_aerofs_growl_GrowlApplicationBridge
     * Method:    _register
     * Signature: (Ljava/lang/String;[B[Ljava/lang/String;[Ljava/lang/String;)V
     */
    JNIEXPORT void JNICALL Java_com_aerofs_growl_GrowlApplicationBridge__1register
    (JNIEnv *, jobject, jstring, jbyteArray, jobjectArray, jobjectArray);
    
    /*
     * Class:     com_aerofs_growl_GrowlApplicationBridge
     * Method:    _unload
     * Signature: ()V
     */
    JNIEXPORT void JNICALL Java_com_aerofs_growl_GrowlApplicationBridge__1release
    (JNIEnv *, jobject);
    
    /*
     * Class:     com_aerofs_growl_GrowlApplicationBridge
     * Method:    _notify
     * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[BIZILjava/lang/String;)V
     */
    JNIEXPORT void JNICALL Java_com_aerofs_growl_GrowlApplicationBridge__1notify
    (JNIEnv *, jobject, jstring, jstring, jstring, jbyteArray, jint, jboolean, jint, jstring);
    
#ifdef __cplusplus
}
#endif
#endif
